---
name: build and publish bvpk-front

on:
  schedule:
    - cron: "15 4 * * *"
  push:
    branches:
      - prod
      - dev
    paths:
      - "front/**"
      - ".github/workflows/build-and-publish-bvpk-front.yml"

env:
  REGISTRY: ghcr.io

jobs:
  build-and-publish-container:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/bvpyro/bvpk-front
          tags: |
            type=sha
            type=ref,event=branch
            type=schedule,pattern={{date 'YYYYMMDD'}}

      - name: Build and push Docker image for front
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: front
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Copy docker-compose.yml to server
        uses: appleboy/scp-action@master
        with:
          host: h2952128.stratoserver.net
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./docker-compose.yml"
          target: "/srv/bvpk/"

      - name:
        uses: appleboy/ssh-action@master
        with:
          host: h2952128.stratoserver.net
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            export CMS_ADMIN_PASSWORD="${{ secrets.CMS_ADMIN_PASSWORD }}"
            export CMS_DB_PASSWORD="${{ secrets.CMS_DB_PASSWORD }}"
            export CMS_KEY="${{ secrets.CMS_KEY }}"
            export CMS_SECRET="${{ secrets.CMS_SECRET }}"
            export EMAIL_PASS="${{ secrets.EMAIL_PASS }}"
            export NOCODB_DB_PASSWORD="${{ secrets.NOCODB_DB_PASSWORD }}"
            export NOCODB_TOKEN="${{ secrets.NOCODB_TOKEN }}"
            export UMAMI_DB_PASSWORD="${{ secrets.UMAMI_DB_PASSWORD }}"
            export UMAMI_HASH_SALT="${{ secrets.UMAMI_HASH_SALT }}"
            docker-compose -f /srv/bvpk/docker-compose.yml pull
            docker-compose -f /srv/bvpk/docker-compose.yml up -d
